apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      automountServiceAccountToken: false
      containers:
      - name: jenkins
        image: asonisg/modified-jenkins:2.249.3-lts
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        env: 
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        volumeMounts:
          - name: jenkins-vol
            mountPath: /var/jenkins_home
      - name: dind
        image: docker:18.05-dind
        securityContext:
         privileged: true
        volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
      volumes:
       - name: jenkins-vol
         emptyDir: {}
       - name: dind-storage
         emptyDir: {}
